twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        site_name: 'My Awesome Site'
        site_url: 'https://www.example.com'
        app_settings: '@App\Services\ApplicationSettings'
when@test:
    twig:
        strict_variables: true
